### PR TITLE
Fix Modulo division

### LINKED ISSUE #28: panic_fmt called with line number
When displaying the line number in panic_fmt, the line number is inaccurate.

We might not be able to fix this.

### PR DESCRIPTION
**Pull request by dnseitz**
The compiler builtin function being called for modulo division
`__aeabi_uidivmod` uses a special calling convention that was not being
adhered to. In order to get around this we must implement the function
in assembly to match the requirements of the calling convention.
The issue was discovered from:
https://github.com/rust-lang-nursery/compiler-builtins/blob/master/src/arm.rs
(See the note at the top of the file)

This fixes #28 and #53 
@pdouglas94 @RJ-Russell

### CODE REVIEW

File: altos-rust/port/cortex-m0/libs/arm/src/math.rs [hunk 1]
```diff
@@ -37,31 +37,72 @@ pub extern "C" fn __aeabi_lmul(a: u64, b: u64) -> u64 {
...
 pub extern "C" fn __aeabi_uidiv(num: u32, den: u32) -> u32 {
-  __aeabi_uidivbase(num, den, false)
+    __aeabi_uidivbase(num, den, false)
 }
 
 #[no_mangle]
-pub extern "C" fn __aeabi_uidivmod(num: u32, den: u32) -> u32 {
-  __aeabi_uidivbase(num, den, true)
+pub extern "C" fn __udivmodsi4(mut num: u32, mut den: u32, rem_p: Option<&mut u32>) -> u32 {
+	let mut quot = 0;
```
Comment (RJ-Russell) [inline altos-rust/port/cortex-m0/libs/arm/src/math.rs]: This file's indentation level does not appear to be offset at 4 spaces at each level.

File: altos-rust/port/cortex-m0/libs/arm/src/math.rs [hunk 2]
```diff
@@ -37,31 +37,72 @@ pub extern "C" fn __aeabi_lmul(a: u64, b: u64) -> u64 {
...
+#[no_mangle]
+#[naked]
+pub unsafe fn __aeabi_uidivmod() {
+    asm!("push {lr}
+          sub sp, sp, #4
+          mov r2, sp
+          bl __udivmodsi4
+          ldr r1, [sp]
+          add sp, sp, #4
+          pop {pc}");
```
Comment (RJ-Russell) [inline altos-rust/port/cortex-m0/libs/arm/src/math.rs]: move the `);` to its own line and align code after with it.

**Comment by RJ-Russell** [comment]
I'm good with this :+1: .. I'll hold off approving it until @pdouglas94 takes a look.

**Review by pdouglas94 — CHANGES_REQUESTED** [review]
I'm getting several compiler errors from this when running `make test`

**Review by pdouglas94 — APPROVED** [review]
I'm not seeing any more errors. Looks good.
